version: '3.9'
services:

#  api:
#    container_name: api
#    image: "graalvm:0.0.1-SNAPSHOT"
#    ports:
#      - "8080:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/custom_db
#      SPRING_DATASOURCE_USERNAME: password
#      SPRING_DATASOURCE_PASSWORD: password

  mysql:
    image: "mysql:8.0"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: custom_db
      MYSQL_USER: password
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}